### ISSUE TITLE
As a user, I want to be able to update and change information in my profile, so that other users can get information about me.

### ISSUE THREAD

**Issue by nsvedberg** [nsvedberg/SocialCircle#20]
Allow users to edit information on their profile.

![Image](https://github.com/user-attachments/assets/50442a63-bfaa-433a-8bdd-ad10b5d75074)

**Acceptance Criteria**

**Given** the user is on their own user profile page,

**When** they enter their new information and click the "save" button,

**Then** they should see the updated information on their profile.

**Comment by LukeHopson** [comment]
![Image](https://github.com/user-attachments/assets/3ac63d2b-c420-4884-b5f1-90fb227665d6)
