### ISSUE TITLE
As a user, I want to be able to view information on other user's profile, so that I can learn more about my fellow users.

### ISSUE THREAD

**Issue by nsvedberg** [nsvedberg/SocialCircle#21]
Allow users to view other user's profile information

![Image](https://github.com/user-attachments/assets/60ace153-0793-4429-8a47-79f5a4b422e1)

**Acceptance Criteria**

**Given** the user is logged into the site

**When** they navigate to another user's profile page,

**Then** they should see information about that user.

**Comment by LukeHopson** [comment]
![Image](https://github.com/user-attachments/assets/b104cfe3-e043-4226-bf9b-c260e1da5835)
