### ISSUE TITLE
As a user, I want to be able to type in the search bar, and see results appear as I am typing, so that I can find clubs and events more responsively.

### ISSUE THREAD

**Issue by nsvedberg** [nsvedberg/SocialCircle#22]
Implement dynamic searching

**Comment by LukeHopson** [comment]
![Image](https://github.com/user-attachments/assets/ede1e2c0-2cc6-49f8-9df2-9c008972b3b6)

**Comment by LukeHopson** [comment]
![Image](https://github.com/user-attachments/assets/b43c9c09-fef0-4b0e-922d-13b1f7fff44e)

**Comment by MarkSchwa** [comment]
![image](https://github.com/user-attachments/assets/4d87a298-5cb4-45ff-9606-6da53d1dd530)

**Comment by LukeHopson** [comment]
Acceptance Criteria

Given the user is on the event or club dashboard

When they type in the search bar

Then events/clubs matching the query should be suggested while typing

**Comment by MarkSchwa** [comment]
completed
