### ISSUE TITLE
As a user, I want to be able to see the members of a club when I am looking at the club information page so I can see if my friends or people I know are in the club

### ISSUE THREAD

**Issue by HugsMackenzie** [nsvedberg/SocialCircle#25]
>Update the Club page to include a list of members

**Comment by LukeHopson** [comment]
![Image](https://github.com/user-attachments/assets/5cf7e8ca-d855-4d68-b318-6c9a8f53d547)

**Comment by LukeHopson** [comment]
![Image](https://github.com/user-attachments/assets/f81a6d3d-0405-4c2d-87e1-103dd803e70d)
Acceptance Criteria

Given the user is logged into the site

When they navigate to an individual club, 

Then they should be able to view a list of members of that club, and navigate to their profiles.

**Comment by LukeHopson** [comment]
Blocked by Ticket #23
