### ISSUE TITLE
As a Club leader hosting an event, I would like to be able to see the list of RSVP'd users so that I can plan accordingly for how many guests will be attending.

### ISSUE THREAD

**Issue by HugsMackenzie** [nsvedberg/SocialCircle#36]

**Comment by LukeHopson** [comment]
Acceptance Criteria

Given the user is logged in

When they view an individual event

Then they can click a button that adds them to an event user list

**Comment by LukeHopson** [comment]
Acceptance Criteria: 
Same as ticket 35?
