### ISSUE TITLE
Check for user permissions prior to club/event creation

### ISSUE THREAD

**Issue by LukeHopson** [nsvedberg/SocialCircle#8]

**Comment by nsvedberg** [comment]
Probably should not just be an if statement. Flask has the @login_required attribute for routes. React probably has something similar.

https://flask-login.readthedocs.io/en/latest/

**Comment by LukeHopson** [comment]
Acceptance Criteria

Given the user is logged in

When they try to edit or delete a event/club/comment

Then they will only be allowed to do so if they are the original poster, or club leader

**Comment by LukeHopson** [comment]
I think we don't do this and let everyone create
